# docker compose file
services:
  robot_base:
    # Interactive shell
    stdin_open: true # docker run -i
    tty: true # docker run -t
    # Needed to display graphical applications
    privileged: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      # docker compose interpolation to env variables
      - AUTONOMY_LAUNCH_PACKAGE=${AUTONOMY_LAUNCH_PACKAGE}
      - AUTONOMY_LAUNCH_FILE=${AUTONOMY_LAUNCH_FILE}
      # --
      - INTERFACE_LAUNCH_PACKAGE=${INTERFACE_LAUNCH_PACKAGE}
      - INTERFACE_LAUNCH_FILE=${INTERFACE_LAUNCH_FILE}
      # --
      - SENSORS_LAUNCH_PACKAGE=${SENSORS_LAUNCH_PACKAGE}
      - SENSORS_LAUNCH_FILE=${SENSORS_LAUNCH_FILE}
      # --
      - PERCEPTION_LAUNCH_PACKAGE=${PERCEPTION_LAUNCH_PACKAGE}
      - PERCEPTION_LAUNCH_FILE=${PERCEPTION_LAUNCH_FILE}
      # --
      - LOCAL_LAUNCH_PACKAGE=${LOCAL_LAUNCH_PACKAGE}
      - LOCAL_LAUNCH_FILE=${LOCAL_LAUNCH_FILE}
      # --
      - GLOBAL_LAUNCH_PACKAGE=${GLOBAL_LAUNCH_PACKAGE}
      - GLOBAL_LAUNCH_FILE=${GLOBAL_LAUNCH_FILE}
      # --
      - BEHAVIOR_LAUNCH_PACKAGE=${BEHAVIOR_LAUNCH_PACKAGE}
      - BEHAVIOR_LAUNCH_FILE=${BEHAVIOR_LAUNCH_FILE}
    deploy:
      # let it use the GPU
      resources:
        reservations:
          devices:
            - driver: nvidia # https://stackoverflow.com/a/70761193
              count: 1
              capabilities: [gpu]
    volumes:
      # display stuff
      - $HOME/.Xauthority:/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      # developer stuff
      - .dev:/home/robot/.dev:rw # developer config
      - .bashrc:/home/robot/.bashrc:rw # bash config
      # - /var/run/docker.sock:/var/run/docker.sock # access docker API for container name
      - ../../common/inputrc:/etc/inputrc:rw # for using page up/down to search through command history
      # autonomy stack stuff
      - ../../common/ros_packages:/home/robot/ros_ws/src/common:rw # common ROS packages
      - ../../common/ros_packages/fastdds.xml:/home/robot/ros_ws/fastdds.xml:rw # fastdds.xml
      - ../ros_ws:/home/robot/ros_ws:rw # robot-specific ROS packages

